### ISSUE TITLE
Implement Memory Operations (`memcpy`, `memset`, `memmove`, `memcmp`)

### ISSUE THREAD

**Issue by kryczkal** [Jlisowskyy/AlkOS#14]
**Description:**
Develop the fundamental memory manipulation functions required by the kernel to handle data operations efficiently.

**Tasks:**
- [x] `memcpy` - Implement memory copy.
- [x] `memset` - Implement memory set.
- [x] `memmove` - Implement memory move.
- [x] `memcmp` - Implement memory comparison.
