### ISSUE TITLE
Develop Kernel Allocators (`malloc`, `free`, `calloc`, `realloc`)

### ISSUE THREAD

**Issue by kryczkal** [Jlisowskyy/AlkOS#15]
**Description:**
Create dynamic memory allocation functions for the kernel to manage memory efficiently.

**Tasks:**
- [ ] `malloc` - Implement dynamic memory allocation.
- [ ] `free` - Implement memory deallocation.
- [ ] `calloc` - Implement allocation and zero-initialization.
- [ ] `realloc` - Implement memory reallocation.
