### ISSUE TITLE
Implement Virtual Memory (VM) and Heap Management

### ISSUE THREAD

**Issue by kryczkal** [Jlisowskyy/AlkOS#17]
**Description:**
Design and manage the virtual memory and heap structures to support dynamic memory allocation and efficient memory usage.

**Tasks:**
- [ ] Design and implement virtual memory management.
- [ ] Setup heap structures and manage heap allocations.
- [ ] Implement heap growth and shrinkage mechanisms.
