### ISSUE TITLE
Stack Smash Detection

### ISSUE THREAD

**Issue by kryczkal** [Jlisowskyy/AlkOS#19]
**Description:**
Implement mechanisms to detect and handle stack smashing attacks to enhance kernel security.

**Tasks:**
- [ ] Implement canary values in stack frames.
- [ ] Check canary integrity on function return.
- [ ] Handle detected stack smashing attempts (e.g., trigger kernel panic).
